# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28f734185fa3a6f4418199a4e81545a53160455fd3ddbd4d3d790550a9dd27a1b211f210a7af215e9d9c1e205fa10f71416bf8945b80ec3bba575f64d11bede0

test:
  secret_key_base: fcf138d1989c7016bb2f52d5254cfc825ea1ccfe82415ef48ae8dadad769e6db5e6faf6ad2c9a4c8311a4f8a89220a7823c7c05818966db324d08e09da62bc54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
